set QT_DIR=C:\Qt\6.9.0\msvc2022_64
set QT_VERSION_MAJOR=6
set QT_VERSION_MINOR=9
set QT_VERSION_PATCH=0
set QT_VERSION_STR=6.9.0
set QT_VERSION=6.9.0

set BUILD_MAJOR_VERSION=25
set BUILD_MINOR_VERSION=1
set BUILD_PATCH_VERSION=0
set BUILD_VERSION_STR=25.1.0
set BUILD_TYPE=Release

set CURRENT_DIR=%cd%
set BUILD_DIR=%cd%\_build\%BUILD_VERSION_STR%
set SOURCE_DIR=%cd%\Sources
set IDE_DIR=%cd%\_ide\LMS

mkdir %BUILD_DIR%
mkdir %IDE_DIR%
cd %IDE_DIR%
cmake %SOURCE_DIR%
cd %CURRENT_DIR%
pause